# Generated by Django 4.0.3 on 2022-05-05 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DimosoApp', '0005_alter_stock_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='category',
            field=models.CharField(blank=True, choices=[('Furniture', 'Furniture'), ('Electrical Equipments', 'Electrical Equipments'), ('Phone', 'Phone')], max_length=100, null=True),
        ),
    ]
