# Generated by Django 4.0.3 on 2022-05-05 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DimosoApp', '0007_category_alter_stock_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='export_to_CSV',
        ),
    ]
