# Generated by Django 4.0.3 on 2022-05-05 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DimosoApp', '0009_stock_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
