# Generated by Django 4.0.3 on 2022-05-06 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DimosoApp', '0011_stockhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
