# Generated by Django 4.0.3 on 2022-05-06 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DimosoApp', '0012_stock_end_date_stock_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
