# Generated by Django 4.0.3 on 2022-05-06 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DimosoApp', '0013_alter_stock_end_date_alter_stock_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockhistory',
            name='last_updated',
            field=models.DateField(auto_now=True),
        ),
    ]
