# Generated by Django 4.0.3 on 2022-05-06 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DimosoApp', '0017_alter_stock_last_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='start_date',
        ),
    ]
