# Generated by Django 4.0.3 on 2022-05-07 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DimosoApp', '0019_stock_end_date_stock_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
