# Generated by Django 4.0.3 on 2022-05-07 00:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('DimosoApp', '0021_remove_stock_end_date_remove_stock_start_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='last_modified',
        ),
        migrations.AlterField(
            model_name='stock',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
