# Generated by Django 4.0.3 on 2022-05-17 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DimosoApp', '0027_address_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='reorder_level',
            field=models.IntegerField(blank=True, default='10', null=True),
        ),
    ]
