# Generated by Django 4.0.3 on 2022-05-18 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DimosoApp', '0028_alter_stock_reorder_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='amount',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='issued_amount',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='receive_amount',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
    ]
