# Generated by Django 4.0.3 on 2022-05-18 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DimosoApp', '0029_stock_amount_stock_issued_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='purchasing_amount',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='sales_amount',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
    ]
