# Generated by Django 4.0.3 on 2022-05-25 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DimosoApp', '0030_stock_purchasing_amount_stock_sales_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=20)),
                ('status', models.BooleanField(max_length=20)),
                ('create_at', models.DateTimeField(max_length=20)),
                ('update_at', models.DateTimeField(max_length=20)),
            ],
        ),
    ]
