# Generated by Django 4.0.3 on 2022-05-25 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DimosoApp', '0031_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='lang',
            field=models.CharField(blank=True, choices=[], max_length=50, null=True),
        ),
    ]
