# Generated by Django 4.0.3 on 2022-06-01 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DimosoApp', '0033_alter_language_code_alter_language_create_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='is_issued',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='is_received',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
