# Generated by Django 4.0.3 on 2022-06-02 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DimosoApp', '0034_stock_is_issued_stock_is_received'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='is_issued',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='is_received',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
