# Generated by Django 4.0.3 on 2022-06-02 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DimosoApp', '0035_alter_stock_is_issued_alter_stock_is_received'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='is_issued',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='stock',
            name='is_received',
            field=models.BooleanField(default=False),
        ),
    ]
