# Generated by Django 4.0.3 on 2022-06-04 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DimosoApp', '0038_contactme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactme',
            name='email',
            field=models.EmailField(blank=True, default='@gmail.com', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='contactme',
            name='phone',
            field=models.CharField(blank=True, default='+255', max_length=13, null=True),
        ),
    ]
