# Generated by Django 4.0.3 on 2022-06-04 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DimosoApp', '0039_alter_contactme_email_alter_contactme_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactme',
            name='message',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='contactme',
            name='subject',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
