# Generated by Django 4.0.3 on 2022-06-04 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DimosoApp', '0040_contactme_message_contactme_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactme',
            name='to_dimoso_email',
            field=models.EmailField(blank=True, default='dimosoeljunior8@gmail.com', max_length=254, null=True),
        ),
    ]
