# Generated by Django 4.0.3 on 2022-06-04 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DimosoApp', '0041_contactme_to_dimoso_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactme',
            name='to_dimoso_email',
            field=models.EmailField(blank=True, default='juniordimoso8@gmail.com', max_length=254, null=True),
        ),
    ]
